name: Windows 11 Emulated Setup with 1TB Dev Drive

on:
  workflow_dispatch

jobs:
  setup:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Set up 1TB Dev Drive (VHDX emulat)
        uses: samypr100/setup-dev-drive@v3
        with:
          drive-size: 1TB
          drive-format: NTFS
          drive-type: Dynamic
          drive-path: "C:\\vhds\\dev_drive.vhdx"
          mount-path: "Z"  
          workspace-copy: false  # Nu folosește spațiul workspace pe discul nou
          native-dev-drive: false
          trusted-dev-drive: false
        continue-on-error: true

      - name: Set fake CPU Name (Intel x-Reon)
        run: |
          Set-ItemProperty -Path "HKLM:\\HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0" -Name "ProcessorNameString" -Value "Intel(R) x-Reon CPU @ 4.00GHz"
        continue-on-error: true

      - name: Set fake RAM display 32GB
        run: |
          New-ItemProperty -Path "HKLM:\\HARDWARE\\DESCRIPTION\\System\\CentralProcessor\\0" -Name "FakePhysicalMemory" -Value "32GB" -PropertyType String -Force
        continue-on-error: true

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force
        continue-on-error: true

      - name: Connect to Tailscale with auth key
        run: |
          & "$env:ProgramFiles\\Tailscale\\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$env:GITHUB_RUN_ID
        continue-on-error: true

      - name: Run FPS Fake Display Overlay
        run: |
          Add-Type -AssemblyName PresentationFramework
          $xaml = @"
          <Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                  WindowStyle="None" AllowsTransparency="True" Background="Transparent"
                  Topmost="True" Left="10" Top="10" Width="120" Height="40" ShowInTaskbar="False">
            <TextBlock x:Name="fpsText" FontSize="24" Foreground="Lime" FontWeight="Bold" />
          </Window>
          "@
          $reader = New-Object System.Xml.XmlNodeReader([xml]$xaml)
          $window = [Windows.Markup.XamlReader]::Load($reader)
          $fpsText = $window.FindName("fpsText")
          $fpsText.Text = "FPS: 180"
          $window.Show()
          while ($true) { Start-Sleep -Seconds 10 }
        continue-on-error: true

      - name: Output system info
        run: |
          Write-Host "=== System Info ==="
          Write-Host "Fake CPU: Intel x-Reon 4.00GHz"
          Write-Host "Fake RAM: 32GB"
          Get-PSDrive -Name C,Z
          Write-Host "Tailscale IP:"
          & "$env:ProgramFiles\\Tailscale\\tailscale.exe" ip -4
          Write-Host "=================="
        continue-on-error: true

      - name: Keep workflow alive
        run: |
          while ($true) {
            Write-Host "Workflow active..."
            Start-Sleep -Seconds 300
          }
        continue-on-error: true
        
